#!/usr/bin/env python3
"""
build_hook.py - Builds and extracts the 64-bit Aero Caption Hook binary package
"""

import subprocess
import struct
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_ROOT = os.path.dirname(SCRIPT_DIR)
C_SOURCE = os.path.join(SCRIPT_DIR, 'sw_aero_hook.c')
OBJ_FILE = os.path.join(WORKSPACE_ROOT, 'scratch', 'sw_aero_hook.o')
BIN_FILE = os.path.join(WORKSPACE_ROOT, 'scratch', 'sw_aero_hook.bin')
OUTPUT_CS = os.path.join(SCRIPT_DIR, 'AeroHookBlob.cs')

def build():
    print("[1] Compiling sw_aero_hook.c with clang...")
    cmd = [
        'clang', '-arch', 'x86_64',
        '-O2',
        '-fno-asynchronous-unwind-tables',
        '-mno-stack-arg-probe',
        '-c', C_SOURCE,
        '-o', OBJ_FILE
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print("Compilation failed:", res.stderr)
        return False

    # Extract __TEXT,__text section bytes from Mach-O object file
    print("[2] Extracting text section from object file...")
    with open(OBJ_FILE, 'rb') as f:
        data = f.read()

    # Mach-O 64-bit parsing
    magic = struct.unpack_from('<I', data, 0)[0]
    assert magic == 0xfeedfacf, f"Not Mach-O 64: {hex(magic)}"
    ncmds = struct.unpack_from('<I', data, 16)[0]
    
    code_bytes = None
    offset = 32
    for _ in range(ncmds):
        cmd, cmdsize = struct.unpack_from('<II', data, offset)
        if cmd == 0x19: # LC_SEGMENT_64
            nsects = struct.unpack_from('<I', data, offset + 64)[0]
            sect_off = offset + 72
            for s in range(nsects):
                sectname = data[sect_off : sect_off+16].rstrip(b'\x00').decode()
                segname = data[sect_off+16 : sect_off+32].rstrip(b'\x00').decode()
                addr, size, file_off = struct.unpack_from('<QQI', data, sect_off + 32)
                if sectname == '__text' and segname == '__TEXT':
                    code_bytes = data[file_off : file_off + size]
                    print(f"Found __text section: size={size} bytes at file offset 0x{file_off:x}")
                    break
                sect_off += 80
        if code_bytes:
            break
        offset += cmdsize

    assert code_bytes is not None, "Failed to locate __text section"

    with open(BIN_FILE, 'wb') as f:
        f.write(code_bytes)
    print(f"Saved binary blob to {BIN_FILE} ({len(code_bytes)} bytes)")

    # Format into C# byte array class AeroHookBlob
    print("[3] Generating AeroHookBlob.cs...")
    hex_lines = []
    chunk_size = 16
    for i in range(0, len(code_bytes), chunk_size):
        chunk = code_bytes[i:i+chunk_size]
        hex_lines.append("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    cs_code = f"""// <auto-generated>
// Generated by build_hook.py. Do not edit manually.
// Code size: {len(code_bytes)} bytes.
// </auto-generated>
namespace WineSW.Daemon {{
    public static class AeroHookBlob {{
        public static readonly byte[] Code = new byte[] {{
{os.linesep.join(hex_lines)}
        }};
    }}
}}
"""
    with open(OUTPUT_CS, 'w', encoding='utf-8') as f:
        f.write(cs_code)
    print(f"Generated {OUTPUT_CS} successfully.")
    return True

if __name__ == '__main__':
    build()
